<?php

/**
 * Implements hook_menu_links_discovered_alter().
 *
 * Remove the admin menu in case the help module is enabled.
 */
function advanced_help_menu_links_discovered_alter(&$links) {

  if (Drupal::moduleHandler()->moduleExists('help')) {
    unset($links['advanced_help.main']);
  }
}

/**
 * Implements hook_modules_installed().
 */
function advanced_help_modules_installed($modules) {
  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  \Drupal::cache('discovery')->invalidate('advanced_help_ini_' . $language);
}