<?php

/**
 * Implements hook_menu_links_discovered_alter().
 *
 * Remove the admin menu in case the help module is enabled.
 */
function advanced_help_menu_links_discovered_alter(&$links) {

  if (Drupal::moduleHandler()->moduleExists('help')) {
    unset($links['advanced_help.main']);
  }
}

/**
 * Implements hook_modules_installed().
 */
function advanced_help_modules_installed($modules) {
  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  \Drupal::cache('discovery')->invalidate('advanced_help_ini_' . $language);
}

/**
 * Implements hook_theme().
 */
function advanced_help_theme() {
  return [
    'advanced_help_topic' => [
      'variables' => [
        'module' => NULL,
        'topic'  => NULL,
        'type'   => 'icon',
      ]
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function advanced_help_preprocess_advanced_help_topic(&$variables) {
  $module = $variables['module'];
  $topic  = $variables['topic'];
  $type   = $variables['type'];

  $advancedHelp = \Drupal::service('plugin.manager.advanced_help');
  $variables['topic_exists'] = $advancedHelp->getTopic($module, $topic);

  switch ($type) {
    case 'icon':
      $variables['text'] = '<span>' . t('Help') . '</span>';
      $variables['class'] = 'advanced-help-link';
      break;

    case 'title':
      $variables['text'] = $info['title'];
      $variables['class'] = 'advanced-help-title';
      break;

    default:
      $variables['class'] = 'advanced-help-title';
      $variables['text'] = $type;
      break;
  }
  //if (user_access('view advanced help popup')) {
    //drupal_add_css(drupal_get_path('module', 'advanced_help') . '/help-icon.css');
//    return l($text, "help/$module/$topic", array(
//        'attributes' => array(
//          'class' => $class,
//          'onclick' => "var w=window.open(this.href, 'advanced_help_window', 'width=" . $info['popup width'] . ",height=" . $info['popup height'] . ",scrollbars,resizable'); w.focus(); return false;",
//          'title' => $info['title'],
//        ),
//        'query' => array('popup' => TRUE),
//        'html' => TRUE)
//    );
  //}
  //elseif (user_access('view advanced help topic')) {
  //}
//  array(
//    'attributes' => array(
//      'class' => $class,
//      'title' => $info['title'],
//    ),
//    'html' => TRUE)
}