<?php
/**
 * @file
 * Provide example help for the advanced help module.
 */

/**
 * Implements hook_menu().
 */
function help_example_menu() {
  // View help topic index.
  $items['admin/help_example'] = array(
    'title' => 'Example help',
    'page callback' => 'help_example_index_page',
    'access arguments' => array('view advanced help index'),
    'weight' => 9,
  );
  return $items;
}

/**
 * Topic index callback.
 */
function help_example_index_page() {
  // Create the question mark icon.
  $output = theme('advanced_help_topic', array(
    'module' => 'help_example',
    'topic' => 'about-example',
    'type' => 'icon',
  ));
  // Append some explanatory text.
  $output .= '&nbsp;' . t('Click the help icon on the left to view a popup help page.');
  return $output;
}
